-- ============================================================================
-- Echo Barrier Hub — Suppliers + Item Catalogue (SRO slice 2)
-- Target project: korylyniwsqtsvzuzydg ("Hubspot Shipping and Stocks") — SHARED.
--
-- PURELY ADDITIVE — two NEW tables only. Touches nothing the live n8n PO Phase 1/2
-- or the snapshot pipelines read or write, so those are unaffected by construction.
--
-- What this adds (both follow the existing po_* picklist pattern: read-all for
-- authenticated, writes via service-role only; seeded here, edited later via UI):
--
--   1. po_suppliers   — the supplier/vendor register (picklist source for supplier
--      & BOM POs). Seeded verbatim from Unleashed "Supplier List" (23/06/2026, 32
--      rows). Overhead vendors (Adobe / Edenred / Slovak Telekom / Stock Journal)
--      and duplicate shadows (BAM, HEND, INVC Ltd) are seeded active = false so the
--      picklist is clean while nothing is lost. Bamida carries its full address +
--      VAT (used by the Bamida supplier-PO doc, which now reads this table).
--
--   2. item_catalog   — the full Unleashed item master (317 rows from the
--      "Product List", 23/06/2026): finished barriers, Bamida manufacturing,
--      printing, raw materials, packaging, services. The picklist source for the
--      BOM / supplier-PO side (slice 3) and the real codes behind the Bamida PO.
--      Normalisations from the PDF: stock-qty columns dropped; a trailing column-
--      artifact dash stripped from codes (`1244 -` → `1244`); six back-to-back
--      wrapped descriptions hand-corrected. currency defaults to EUR (SRO).
--
-- Distinct from the existing tables (left UNTOUCHED): po_product_catalog = the
-- depot-orderable finished-goods picklist (14 NA SKUs); product_code_master =
-- the per-entity Xero code cross-reference. item_catalog is the SRO/supplier-side
-- item universe, a separate namespace.
-- ============================================================================

-- ----------------------------------------------------------------------------
-- 1. po_suppliers
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.po_suppliers (
  id              uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  code            text NOT NULL UNIQUE,
  name            text NOT NULL,
  city            text,
  country         text,
  currency        text,
  address         text,           -- full multiline address (only some known, e.g. Bamida)
  tax_number      text,           -- VAT / IČ DPH where known
  xero_contact_id text,           -- hardcoded into the n8n Xero flow once fetched
  active          boolean NOT NULL DEFAULT true,
  created_at      timestamptz NOT NULL DEFAULT now()
);

INSERT INTO public.po_suppliers (code, name, city, country, currency, address, tax_number, active) VALUES
  ('Acoustical Surfaces Inc', 'Acoustical Surfaces Inc', null, null, 'EUR', null, null, true),
  ('Adobe Systems Software Ireland Ltd', 'Adobe Systems Software Ireland Ltd', 'Dublin 24', 'Ireland', 'EUR', null, null, false),
  ('ANOT', 'ANO Tasky', null, 'Slovakia', 'EUR', null, null, true),
  ('BAM', 'Bamida sro', null, 'Slovakia', 'EUR', null, null, false),
  ('BAMIDA, s.r.o.', 'BAMIDA, s.r.o.', 'Prešov', 'Slovakia', 'EUR', E'Košická 28\n080 01 Prešov\nSlovakia', 'SK2022392372', true),
  ('cargo - partner SR, s.r.o.', 'cargo - partner SR, s.r.o.', 'Bratislava - mestská časť Petržalka', 'Slovakia', 'EUR', null, null, true),
  ('Cargomind', 'Cargomind', null, null, 'EUR', null, null, true),
  ('EBG', 'Echo Barrier Group Limited', null, 'Slovakia', 'EUR', null, null, true),
  ('EBUK', 'Echo Barrier Limited', null, null, 'EUR', null, null, true),
  ('Edenred Slovakia, s.r.o.', 'Edenred Slovakia, s.r.o.', 'Bratislava', 'Slovakia', 'EUR', null, null, false),
  ('G & R HENDERSON & CO LTD', 'G & R HENDERSON & CO LTD', 'Stockport', null, 'GBP', null, null, true),
  ('Gregg Murfin', 'Gregg Murfin', 'Hong Kong', 'Hong Kong', 'EUR', null, null, true),
  ('HEND', 'G & R Henderson', null, null, 'EUR', null, null, false),
  ('INVC', 'Industrial Noise & Vibration Centre Limited', null, 'Slovakia', 'EUR', null, null, true),
  ('INVC Ltd', 'Industrial Noise & Vibration Centre', null, 'Slovakia', 'GBP', null, null, false),
  ('Jilana A.S', 'Jilana A.S', null, 'Slovakia', 'EUR', null, null, true),
  ('L Trans', 'L Trans', null, null, 'EUR', null, null, true),
  ('Lukacko Jan', 'Lukacko Jan', null, null, 'EUR', null, null, true),
  ('Moriss S.R.O', 'Moriss S.R.O', null, null, 'EUR', null, null, true),
  ('NEVEON Slovakia s.r.o.', 'NEVEON Slovakia s.r.o.', null, 'Slovakia', 'EUR', null, null, true),
  ('PEGAS', 'Pegasus International', null, 'Slovakia', 'EUR', null, null, true),
  ('Píla Šebastovce', 'DP Work s.r.o.', 'Košice', 'Slovakia', 'EUR', null, null, true),
  ('POLY', 'Polyspool', null, null, 'EUR', null, null, true),
  ('POLY Spol. S.R.O', 'POLY Spol. S.R.O', null, null, 'EUR', null, null, true),
  ('R & C Solutions S.R.O', 'R & C Solutions S.R.O', null, null, 'EUR', null, null, true),
  ('SA-KO Wood s.r.o', 'SA-KO Wood s.r.o', null, null, 'EUR', null, null, true),
  ('SAM', 'Samer & Co. Shipping, s.r.o.,', null, 'Slovakia', 'EUR', null, null, true),
  ('SK-Tex spol. s r.o.', 'SK-Tex spol. s r.o.', 'Bratislava', 'Slovakia', 'EUR', null, null, true),
  ('Slovak Telekom, a.s.', 'Slovak Telekom, a.s.', null, null, 'EUR', null, null, false),
  ('Stock Journal', 'Stock Journal', null, null, 'EUR', null, null, false),
  ('TRANSPORT', 'TRANSPORT', null, 'Slovakia', 'EUR', null, null, true),
  ('VLDS s.r.o', 'VLDS s.r.o', null, null, 'EUR', null, null, true)

ON CONFLICT (code) DO UPDATE
  SET name = EXCLUDED.name,
      city = EXCLUDED.city,
      country = EXCLUDED.country,
      currency = EXCLUDED.currency,
      address = COALESCE(EXCLUDED.address, public.po_suppliers.address),
      tax_number = COALESCE(EXCLUDED.tax_number, public.po_suppliers.tax_number);
      -- NB: `active` is intentionally NOT reset on conflict (replay-safe — preserves
      -- a later UI activate/deactivate), matching item_catalog's conflict clause.

-- ----------------------------------------------------------------------------
-- 2. item_catalog (full Unleashed item master)
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.item_catalog (
  code          text PRIMARY KEY,
  description   text,
  product_group text,
  base_unit     text,
  currency      text NOT NULL DEFAULT 'EUR',
  active        boolean NOT NULL DEFAULT true,
  created_at    timestamptz NOT NULL DEFAULT now()
);

INSERT INTO public.item_catalog (code, description, product_group, base_unit) VALUES
  ('[MANBUL]', 'Bamida Manufacturing Costs EB BULLBARRIER 3m', 'Bamida Manufacturing', 'Piece'),
  ('04-934', 'Tesa 04 934 (caoutchouc - grid)', 'Double Sided Tape', 'Ln Meter'),
  ('1244', 'Heytex 5573-9006 (silver)', 'PVC', 'Sq Meter'),
  ('1436', 'V 25 mm White Fuzzy', 'Velcro', 'EA'),
  ('1437', 'V 25 mm White Hook', 'Velcro', 'EA'),
  ('1566', 'V 100 mm Black Hook 102', 'Velcro', 'EA'),
  ('1567', 'V 100 mm Black Fuzzy 102', 'Velcro', 'EA'),
  ('1596', 'L & B 9145-682 mesh', 'Bamida Mesh', 'Sq Meter'),
  ('1597', 'L&B 8540-958 (white)', 'PVC', 'Sq Meter'),
  ('1599', 'White Strongbond', 'Thread', 'Ln Meter'),
  ('1620', 'Orange NC-Tech 20 (3516)', 'Thread', 'Ln Meter'),
  ('1621', 'White NC-Tech 34', 'Thread', 'Ln Meter'),
  ('1622', 'Black NC-Tech 20', 'Thread', 'Ln Meter'),
  ('1636', 'L&B 8509- 636(green)', 'PVC', 'Sq Meter'),
  ('1715', 'Retrox Fireproof TRUMF FRc 50mm', 'Reflective Stripes', 'EA'),
  ('1761', 'Strap PP 10/1/25 White 25mm', 'Welt', 'Ln Meter'),
  ('1764', 'L&B 8509-907 (white)', 'PVC', 'Sq Meter'),
  ('1781 Metal frames', 'Metal Frames for Pallets', 'Bamida Manufacturing', 'EA'),
  ('1838 Rachetts', 'Ratchets for use in container', 'Bamida Manufacturing', 'EA'),
  ('1935', 'Orange NC-Tech 20 (0450)', 'Thread', 'Ln Meter'),
  ('1948', 'FS25AC Black plastic buckle 25mm', 'Buckle', 'EA'),
  ('1972', 'PVC Soft Stripes Standart 2/200', 'PVC Strip', 'Ln Meter'),
  ('1973', 'PVC Soft Stripes Standart 3/300', 'PVC Strip', 'Ln Meter'),
  ('1994', 'SATTLER 622 800 320', 'PVC', 'Sq Meter'),
  ('2013', 'L&B 7806-905 (black) 5342', 'PVC', 'Sq Meter'),
  ('2014', 'L&B 7807 - 905 (black) 5340', 'PVC', 'Sq Meter'),
  ('263', 'Galvanized 10mm', 'Eyelets', 'EA'),
  ('264 Galv 12mm', 'Galv Eyelets 12mm', 'Eyelets', 'EA'),
  ('266 Galv', '25mm Galvanised Eyelets', 'Eyelets', 'EA'),
  ('269', 'Brass 25mm', 'Eyelets', 'EA'),
  ('300', 'Plastic pad under the rivet 35.25', 'Pad', 'EA'),
  ('30-0980', 'Beige Synton 30-0980', 'Thread', 'Ln Meter'),
  ('301', 'Plastic pad under the rivet 35.51', 'Pad', 'EA'),
  ('303', 'Rivet Tappped 34.10', 'Rivets', 'EA'),
  ('34', 'Black NC-Tech 34', 'Thread', 'Ln Meter'),
  ('361', 'Iron Screw - 7504K VZ4 8x24', 'Connecting material', 'EA'),
  ('371', 'Wood Screw DIN. ŽL 5x50', 'Connecting material', 'EA'),
  ('378', 'Pad ZI 5x30', 'Connecting material', 'EA'),
  ('418', 'V 50 mm White Hook', 'Velcro', 'EA'),
  ('419', 'V 50 mm White Fuzzy', 'Velcro', 'EA'),
  ('420', 'V 38 mm Black Hook', 'Velcro', 'EA'),
  ('421', 'V 38 mm Black Fuzzy', 'Velcro', 'EA'),
  ('422', 'V 25 mm Black Fuzzy', 'Velcro', 'EA'),
  ('423', 'V 25 mm Black Hook', 'Velcro', 'EA'),
  ('51-996', 'Tesa 51 966 (acryl - new)', 'Double Sided Tape', 'Ln Meter'),
  ('60-0504', 'Red Synton 60-0504', 'Thread', 'Ln Meter'),
  ('605', 'Strap PP 31S900 10/1/25 Black 25mm', 'Welt', 'Ln Meter'),
  ('606', 'Strap PP 31S900 10/1/40 Black 40mm', 'Welt', 'Ln Meter'),
  ('607', 'V 38 mm White Fuzzy', 'Velcro', 'EA'),
  ('608', 'V 38 mm White Hook', 'Velcro', 'EA'),
  ('610', 'V 50 mm Black Fuzzy', 'Velcro', 'EA'),
  ('611', 'V 50 mm Black Hook', 'Velcro', 'EA'),
  ('612', 'White Synton 30-2285', 'Thread', 'Ln Meter'),
  ('613', 'Black Synton 30-2285', 'Thread', 'Ln Meter'),
  ('614', 'Black Strongbond V2035', 'Thread', 'Ln Meter'),
  ('616', 'Orange Strongbond 20 (3516)', 'Thread', 'Ln Meter'),
  ('618', 'Stretch Foil', 'Connecting material', 'EA'),
  ('619', 'Tesa 64 620 (caoutchouc)', 'Double Sided Tape', 'Ln Meter'),
  ('620', 'Retrox Fireproof TRUMF FRc 25mm', 'Reflective Stripes', 'EA'),
  ('679', 'Tesa 51 970 (acryl - substitute)', 'Double Sided Tape', 'Ln Meter'),
  ('707', 'Runner Double-Sided Zipper', 'Runner', 'EA'),
  ('720', 'L&B 8540-606 (green)', 'PVC', 'Sq Meter'),
  ('7407', 'Atol1 5347 (7407)', 'Bamida Mesh', 'Sq Meter'),
  ('782-8956', 'Ferrari 782-8956 (white)', 'PVC', 'Sq Meter'),
  ('824', 'L&B 8540-370 (red)', 'PVC', 'Sq Meter'),
  ('826', 'L&B 8540-905 (black)', 'PVC', 'Sq Meter'),
  ('827', 'L&B 8540-543 (5341) (blue)', 'PVC', 'Sq Meter'),
  ('891', 'Heytex 5573-3002 (red)', 'PVC', 'Sq Meter'),
  ('896', 'Ferrari 362 1323 White mesh', 'Bamida Mesh', 'Sq Meter'),
  ('898', 'Ferrari 362 RAL 5015 Blue Mesh', 'Bamida Mesh', 'Sq Meter'),
  ('899', 'Ferrari 362 RAL 1075 Balck Mesh', 'Bamida Mesh', 'Sq Meter'),
  ('900', 'Ferrari 362 RAL 6005 green Mesh', 'Bamida Mesh', 'Sq Meter'),
  ('901', 'Ferrari 782-8389 (white-grey)', 'PVC', 'Sq Meter'),
  ('902', 'Ferrari 705-1063 (orange)', 'PVC', 'Sq Meter'),
  ('929', 'L&B 8540-543 (5240) (blue)', 'PVC', 'Sq Meter'),
  ('934', 'Red NC-Tech 20 (0503)', 'Thread', 'Ln Meter'),
  ('95', 'L&B 8540-636 (green)', 'PVC', 'Sq Meter'),
  ('961', 'Strap PP 10/1/40 White 40mm', 'Welt', 'Ln Meter'),
  ('ACRP', 'ACRP NT BARRIER 054x06000', 'PVC', 'Sq Meter'),
  ('ACS', 'Acoustic Consultant Services', null, null),
  ('AIRF', 'Air Freight', null, null),
  ('B4', 'ECHO BARRIER B4 - Breaker barrier manufacturing cost', null, null),
  ('BAMCSG', 'Bamida Manufacturing Cutting Station Complete', 'Bamida Manufacturing', 'EA'),
  ('BAMH10JAP', 'Bamida H10 Japan', 'Bamida Manufacturing', 'EA'),
  ('BAMMANCSCOMP', 'Bamida Manufacturing CS Compact', 'Bamida Manufacturing', 'EA'),
  ('BnM', 'Blok N Mesh', 'Finished Barriers', 'EA'),
  ('BPR', 'Big Pack - ROLL 1580mm', 'Slovak Cotton', 'Ln Meter'),
  ('CBCS', 'Creat Box for CS R10 2000 x 1850 x 1000 (inside) with shelve', null, null),
  ('CBCSC', 'Creat Box for CS Compact 2550 x 1500 x 1000 (inside) with shelve', null, null),
  ('CH8', 'Chapter 8 Sewable', 'Echo Barrier own Stock', 'EA'),
  ('CLOGO', 'Customer Logo', 'Finished Barriers', 'EA'),
  ('CNM', 'Computer Noise Modelling', null, null),
  ('COMPFRM', 'COMPACT FRAME', 'EB Admin', 'EA'),
  ('CS Compact', 'Cutting Station Compact', 'Finished Barriers', 'EA'),
  ('CS End Barrier', 'Cutting Station End Barrier with Butchers Door', 'Finished Barriers', 'EA'),
  ('CSB', 'Cutting Station Barrier', 'Finished Barriers', 'EA'),
  ('CSC ROOF SKIN', 'Cuting station compact roof skin', null, null),
  ('CSG', 'Cutting Station Complete', 'Finished Barriers', 'EA'),
  ('CSMIRR', 'Cutting Station Mirror Barrier', 'Finished Barriers', 'EA'),
  ('CSP', 'Cuting Station Plus', 'Finished Barriers', 'EA'),
  ('CSP DOOR', 'Manufacturing cost for Cuting Station Plus Door', null, null),
  ('CSP VELCRO COVER GORATEX', 'Manufacturing cost for Cuting Station Plus Velcro Cover Goratex', null, null),
  ('CSP VELCRO COVER PVC', 'Manufacturing cost for Cuting Station Plus Velcro Cover PVC', null, null),
  ('CSR Acoustic Roof Barrier', 'Cutting Station Acoustic Roof barrier', 'Finished Barriers', 'EA'),
  ('CSS Side Barriers', 'Cutting Station Side barriers 2 per Station', 'Finished Barriers', 'EA'),
  ('CSVENT', 'Cutting Station Ventilation Barrier', 'Finished Barriers', 'EA'),
  ('CUSTOM COST', 'Representation in custom proces', null, null),
  ('Delivery', 'Delivery of Goods', 'EB Admin', 'EA'),
  ('DT', 'RFID Chip DATA-TAG', 'Datatags', 'EA'),
  ('EB3', 'EB3 PES INFILL', 'Acoustic Foam', 'EA'),
  ('EB3 / 800 PES ND', 'Senizol EB3 / 800 (1000mm x 1580 mm)', 'PES Infill', 'EA'),
  ('EBB', 'Bungies', 'Bungies', 'EA'),
  ('EBH', 'Echo Barrier Reverse Hooks', 'Hooks', 'EA'),
  ('EBHJAP', 'Japan Hooks', 'Hooks', 'EA'),
  ('EBHSTD', 'Hooks EU', 'Hooks', 'EA'),
  ('EBSCX', 'Echo Barrier Security Cable 7M. (23Ft)', 'Hooks', 'EA'),
  ('EBSXCL', 'Echo barrier Security Cable 40FT ( 12m)', 'Hooks', 'EA'),
  ('EBVFK', 'Echo Barrier Vertical Fitting Kits', 'Hooks', 'EA'),
  ('ESA800-5FAULT', 'Jilana ESA 800 5 - ROLL 960 mm', 'Non Woven Textile', 'Ln Meter'),
  ('ESA800-f', 'Jilana ESA 800 5 - ROLL 960 mm', 'Non Woven Textile', 'Ln Meter'),
  ('EU 3.5', 'Echo Barrier EU 3.5', 'Finished Barriers', 'EA'),
  ('EUR1', 'Documentation', null, null),
  ('FEET', 'Feet for Fences', null, 'EA'),
  ('FENCE', 'Fence for barriers', null, 'EA'),
  ('FM829', 'FM 829 Gortex Grey', 'Gortex', 'Ln Meter'),
  ('FOAM N1830 TL 20', 'N1830 TL20 1000x1580 mm 16-18 kg/m3', null, 'Piece'),
  ('FOAM N1830 TL 25', 'N1830 TL25 1000x1580 mm 16-18 kg/m3', null, 'Piece'),
  ('GREYM', 'Grey material', 'Gortex', 'Ln Meter'),
  ('GS1', 'Gens Set Enclosure', 'Finished Barriers', 'EA'),
  ('GSEG', 'Gen Set Extension - Green', 'Finished Barriers', 'EA'),
  ('H10', 'Echo Barrier H10', 'Finished Barriers', 'EA'),
  ('H10Blue', 'Echo Barrier H10 in Blue', 'Finished Barriers', 'EA'),
  ('H10BlueEB3', 'Echo Barrier H10 in Blue withEB3', 'Finished Barriers', 'EA'),
  ('H10GMQ', 'H10 green Mutliquip', 'Finished Barriers', 'EA'),
  ('H10Green', 'Echo Barrier H10 Green', 'Finished Barriers', 'EA'),
  ('H10JAPANGREEN', 'H10 Japan Green', 'Finished Barriers', 'EA'),
  ('H10JAPLOGO', 'H10 Japan with logo', 'Finished Barriers', 'EA'),
  ('H11 MAN', 'Manufacturing cost of Echo Barrier H11', null, null),
  ('H11 Print', 'Printing cost of Echo barrier H11', null, null),
  ('H20 Roof', 'Manufacturing cost for H20 roof', null, null),
  ('H2G', 'Echo Barrier H2 Series Green', 'Finished Barriers', 'EA'),
  ('H2ORSET', 'Roof Set H2O: Roof Cover + Roof Acoustic Barrier', null, null),
  ('H3GREEN', 'Echo Barrier H3 Green', 'Finished Barriers', 'EA'),
  ('H4Black', 'H4 in Black', 'Finished Barriers', 'EA'),
  ('H4BLUE', 'H 4 SERIES BLUE PVC & MEMBRANE', 'Finished Barriers', 'EA'),
  ('H4BLUEVELCRO', 'H 4 SERIES BLUE WITH VALCRO', 'Finished Barriers', 'EA'),
  ('H4GREEN', 'H 4 SERIES GREEN', 'Finished Barriers', 'EA'),
  ('H4GREENVLACRO', 'H 4 SERIES GREEN WITH VALCRO', 'Finished Barriers', 'EA'),
  ('H5551', 'Heytex H5551 (biela)', 'PVC', 'Sq Meter'),
  ('H5BLUE', 'H5 Series Blue PVC and Membrane', 'Finished Barriers', 'EA'),
  ('H5GREEN', 'H5 Series, Green with Black Membrane', 'Finished Barriers', 'EA'),
  ('H6GREEN', 'H6 Sonic green', 'Finished Barriers', 'EA'),
  ('H8EB3', 'H8EB3Green', 'Finished Barriers', 'EA'),
  ('H8Green', 'Echo Barrier H8 Green', 'Finished Barriers', 'EA'),
  ('H9', 'Echo Barrier H9', 'Finished Barriers', 'EA'),
  ('H9EB3GREEN', 'H9 Green with EB3', 'Finished Barriers', 'EA'),
  ('H9GMQ', 'H9 green mulitqip', 'Finished Barriers', 'EA'),
  ('H9GOC', 'H9 Green', 'Finished Barriers', 'EA'),
  ('H9GREEN', 'Echo Barrier H9 Green', 'Finished Barriers', 'EA'),
  ('H9GUSA', 'H9 Green USa', 'Echo Barrier own Stock', 'EA'),
  ('H9JAPANGREEN', 'H9 Series Green Japan Only', 'Finished Barriers', 'EA'),
  ('H9JAPBI', 'H9 Japan Blue Itochu', 'Finished Barriers', 'EA'),
  ('H9X MAN', 'Manufacturing cost of Echo Barrier H9X', null, null),
  ('H9X PRINT', 'Printing cost of Echo barrier H9X', null, null),
  ('HEX FRAME', 'Frame (Fence) for H-EX', null, 'EA'),
  ('HT 3.5', 'Echo Barrier HT 3.5', 'Finished Barriers', 'EA'),
  ('HWRBB', 'Heavy Weight with Rubber', 'PES Infill', 'Ln Meter'),
  ('Logo', 'Customer Logo', 'Finished Barriers', 'EA'),
  ('MAN P1', 'ECHO BARRIER P1 - Breaker barrier manufacturing cost', null, null),
  ('MANB1X', 'ECHO BARRIER B1 X - Breaker barrier manufacturing cost', null, null),
  ('MANB6', 'ECHO BARRIER B6_AMS - Breaker barrier manufacturing cost', null, null),
  ('MANBAM', 'Bamida Manufacturing Costs', null, null),
  ('MANBULC', 'Bamida Manufacturing Costs EB BULLBARRIER CORNER', 'Bamida Manufacturing', 'Piece'),
  ('MANCS1335L', 'manufacturing cost CS barrier 1335 left', null, null),
  ('MANCS1335R', 'Manufacturing cost CS barrier 1335 Right', null, null),
  ('MANCS1823', 'Bamida Manufacturing Cost Cutting Station Barrier', 'Bamida Manufacturing', 'EA'),
  ('MANCSCEND', 'Manufacturing price CSC END Barrier doors', null, null),
  ('MANCSEND1830', 'Bamida Manufacturing Cost CS End barrier 1830', 'Bamida Manufacturing', 'EA'),
  ('MANCSM1826', 'Bamida Manufacturing Charge Cutting Station Mirror 1826', 'Bamida Manufacturing', 'EA'),
  ('MANCSR.1833', 'Bamida Manufacturing Cost Roof barrier 1833', 'Bamida Manufacturing', 'EA'),
  ('MANCSS1829', 'Manufacturing Cutting Station Barrier 2 Per Station', 'Bamida Manufacturing', 'EA'),
  ('MANCSV1827', 'Manufacturing Cutting Station Ventilation Barrier 1827', 'Bamida Manufacturing', 'EA'),
  ('MAND11', 'manufacturing costs Barrier D11', null, 'EA'),
  ('MANGS1', 'Manufacturing gen Set S1', 'Bamida Manufacturing', 'EA'),
  ('MANGSE', 'Manufacturing Gen Set EXtension', 'Bamida Manufacturing', 'EA'),
  ('MANGSM1', 'Manufacturing gen Set M1', 'Bamida Manufacturing', 'EA'),
  ('MANH10', 'Bamida Manufacturing Cost H10', 'Bamida Manufacturing', 'EA'),
  ('MANH12', 'Manufacturing cost barrier H12', null, 'EA'),
  ('MANH2', 'Manufacturing Cost Standard', 'Bamida Manufacturing', 'EA'),
  ('MANH4', 'Bamida Manufacturing H4 Non Valcro', 'Bamida Manufacturing', 'EA'),
  ('MANH4V', 'MANUFACTURING H4 BARRIERS WITH VLACRO', 'Bamida Manufacturing', 'EA'),
  ('MANH5JAP', 'Bamida Manufacturing H5 Japan', 'Bamida Manufacturing', 'EA'),
  ('MANH6', 'Bamida Manufacturing H6 Sonic', 'Bamida Manufacturing', 'EA'),
  ('MANH8', 'Bamida Manufacturing H8', 'Bamida Manufacturing', 'EA'),
  ('MANH8MINI', 'Manufacturing cost H8 mini', null, null),
  ('MANH9', 'Bamida Manufacturing cost H9', 'Bamida Manufacturing', 'EA'),
  ('MANH9W', 'Bamida Manufacturing cost H9W', 'Bamida Manufacturing', 'EA'),
  ('MANLCND', 'Manufacturing Low Cost Noise Defender', 'Bamida Manufacturing', 'EA'),
  ('MANMINIH10MQ', 'Manufacturing cost H10 mini barrier', 'Bamida Manufacturing', 'EA'),
  ('MANMINIH9MQ', 'Manufacturing Cost Mini H9 MQ', 'Bamida Manufacturing', 'EA'),
  ('MANND', 'Bamida Manufacturing Noise Defender', 'Bamida Manufacturing', 'EA'),
  ('MANNDmini', 'manufacturing cost for ND mini 210x280 mm (sample)', null, null),
  ('MANPB3', 'Manufacturing PB3', 'Bamida Manufacturing', 'EA'),
  ('MANPB3X', 'Manufacturing cost PB3X barrier', 'Bamida Manufacturing', 'EA'),
  ('MANTB1', 'Manufacturing TB1', 'Bamida Manufacturing', 'EA'),
  ('MANV1', 'Manufacturing V1', 'Bamida Manufacturing', 'EA'),
  ('MANV2', 'Manufacturing cost V2', 'Bamida Manufacturing', 'EA'),
  ('MARK', 'Marking of barrier', null, null),
  ('MH8EX', 'Manufacturing cost of barrier H8 Extension 3650x1237,5 mm', null, null),
  ('MISS', 'Made in SLovakia sticker for USA', 'Printing', 'EA'),
  ('MQMINH9', 'H9 Mini Sample HQ', 'Finished Barriers', 'EA'),
  ('N2130', 'N2130 - (white) - CUT SAMPLES', 'Acoustic Foam', 'EA'),
  ('N2538', 'N2538 - (lila) - CUT SAMPLES', 'Acoustic Foam', 'EA'),
  ('NDD100', 'Noise Defender dB-RD 100', null, null),
  ('NDEB3BLUE', 'Noise Defender EB3/800 2019 Blue', 'Finished Barriers', 'EA'),
  ('NDLC2018', 'Noise Defender low Cost', 'Finished Barriers', 'EA'),
  ('NDNW2018BLUE', 'Noise Defender Non Woven Infill Blue', 'Finished Barriers', 'EA'),
  ('NDS100', 'Single Noise Defender dB-RS100', 'Bamida Manufacturing', null),
  ('NDSC2018BLUE', 'Noise Defender Slovak Cotton Blue', 'Finished Barriers', 'EA'),
  ('NDT100', 'Tripple Noise Defender dB-RT100', 'Bamida Manufacturing', null),
  ('NPRT MAN', 'Noise Protector RT Manufacturing cost', null, null),
  ('NPRT PRINT', 'Noise Protector RT Printing cost', null, null),
  ('P200FR BLACK', 'P 200 FR (black )', 'Gortex', 'Ln Meter'),
  ('P200FR GREY', 'P 200 FR (grey)', 'Gortex', 'Ln Meter'),
  ('P200FR ORNAGE', 'P200FR (orange)', 'Gortex', 'Ln Meter'),
  ('P200FR WHITE', 'P 200 FR (white)', 'Gortex', 'Ln Meter'),
  ('P200FR YELLOW', 'P 200 FR (yellow)', 'Gortex', 'Ln Meter'),
  ('PALCS', 'Wooden fyto pallet for CS R10 (2100x1800 mm)', null, null),
  ('PALCSP', 'Wooden fyto pallet for CS Plus (2600x1850 mm)', null, null),
  ('PALL', 'Palet', null, 'Piece'),
  ('Pallet', 'Wooden Pallet ISPM15 2100 x 1360 x 150 mm', 'Connecting material', 'EA'),
  ('Pallet COVERs', 'covers for pallets', 'Bamida Manufacturing', 'EA'),
  ('PB3', 'Echo Barrier PB3', 'Finished Barriers', 'EA'),
  ('PC350FR BLACK', 'PC 350 FR (black)', 'Gortex', 'Ln Meter'),
  ('PC350FR BLUE', 'PC 350 FR (blue)', 'Gortex', 'Ln Meter'),
  ('PC350FR BOTTLE GREEN', 'PC350FR / Colour Bottle Green / Grade 6 / Width 152cm', 'Gortex', 'Ln Meter'),
  ('PC350FR GR6', 'PC350FR Grade 6 /2,1m (600*600 PU 2,1m) FR/WR/ Solution Dyed', 'Gortex', 'Ln Meter'),
  ('PC350FR GREY', 'PC 350 FR (grey)', 'Gortex', 'Ln Meter'),
  ('PC350FR MAROON', 'PC350FR MAROON', 'Gortex', 'Ln Meter'),
  ('PC350FR ROYAL BLUE', 'PC 350 FR Royal (blue)', 'Gortex', 'Ln Meter'),
  ('PES', 'PES infill 100% recycled synthetic', 'PES Infill', 'Piece'),
  ('PGA250 ORNAGE', 'PGA 250 (orange with grid)', 'Gortex', 'Ln Meter'),
  ('PGA250 YELLOW', 'PGA 250 (yellow with grid)', 'Gortex', 'Ln Meter'),
  ('PH8EX', 'Printing cost of barrier H8 Extension 3650x1237,5 mm', null, null),
  ('PKG', 'Palletising - Reinforced ISPM 15 ( Size 1400mm x 2200mm x 2500mm)', 'Printing', 'EA'),
  ('PNDD100', 'UV Print Noise Defender dB-RD 100', null, null),
  ('PNDS100', 'Printing Single Noise Defender dB-RS100', null, null),
  ('PNDT100', 'Printing Tripple Noise Defender dB-RT100', null, null),
  ('PRBnM', 'Printing BlokNMesh', 'Printing', 'EA'),
  ('PREU 3.5', 'Printing EB EU 3.5 barrier', null, null),
  ('PRHT 3.5', 'Printing Echo Barrier HT 3.5', null, null),
  ('PRI P1', 'ECHO BARRIER P1 - Breaker barrier Printing cost', null, null),
  ('PRIB1X', 'ECHO BARRIER B1 X - Breaker barrier Printing cost', null, null),
  ('PRIB4', 'ECHO BARRIER B4 - Breaker barrier Printing cost', null, null),
  ('PRIB6', 'ECHO BARRIER B6_AMS - Breaker barrier Printing cost', null, null),
  ('PRIBUL', 'Bamida Printing Costs EB BULLBARRIER 3m', 'Bamida Manufacturing', 'Piece'),
  ('PRIBULC', 'Bamida Printing Costs EB BULLBARRIER CORNER', 'Bamida Manufacturing', 'Piece'),
  ('PRICS1335.1829', 'Printing Cutting Station Side 2 per Station', null, null),
  ('PRICS1335L', 'Printing cost CS barrier 1335 Left', null, null),
  ('PRICS1335R', 'Printing cost CS barrier 1335 Right', null, null),
  ('PRICSB1823', 'Printing Cutting Station barrier 1823', 'PVC', 'EA'),
  ('PRICSCEND', 'Printing cost CSC END Barrier doors', null, null),
  ('PRICSCOMPACT', 'Printing CS Compact', 'Printing', 'EA'),
  ('PRICSE1830', 'Printing Cutting Station End Barrier 1830', 'Printing', 'EA'),
  ('PRICSG', 'Printing Complete Cutting Station', 'Printing', 'EA'),
  ('PRICSM1826', 'printing Cutting Station Mirror 1826', 'Printing', 'EA'),
  ('PRICSP', 'Printing Cuting Station Plus', 'Printing', 'EA'),
  ('PRICSP DOOR', 'Printing cost for Cuting Station Plus Door', 'Printing', 'EA'),
  ('PRICSV1827', 'Printing Cutting Station Ventilation Barrier', 'Printing', 'EA'),
  ('PRIGS1', 'Printing Gen Set M1', 'Printing', 'EA'),
  ('PRIGSE', 'Printing gen Set Extension', 'Printing', 'EA'),
  ('PRIGSM1', 'Printing Gen Set M1', 'Printing', 'EA'),
  ('PRIH8', 'Printing H8', 'Printing', 'EA'),
  ('PRIH8MINI', 'Printing cost H8 mini', null, null),
  ('PRIJAP', 'Printing Japan', 'Printing', 'EA'),
  ('PRILCND', 'Printing Low Cast Noise Defender', 'Printing', 'EA'),
  ('PRIMINIH10MQ', 'Printing costs H10 mini', 'Printing', 'EA'),
  ('PRIMINIH9MQ', 'Printing Mini H9 MQ', 'Printing', 'EA'),
  ('PRIMQ', 'Printing MQ Sticker', null, null),
  ('PRIND', 'Printing Noise Defender', 'Printing', 'EA'),
  ('PRINDmini', 'Printing cost for ND mini 210x280 mm (sample)', null, null),
  ('PRINH12', 'Printing cost barrier H12', null, 'EA'),
  ('PRINTD11', 'Printing costs Echo barrier D11', null, 'EA'),
  ('PRINTLGOG', 'Bamida Cost Customer Logo', 'Printing', 'EA'),
  ('PRIPB3', 'Printing PB3', 'Printing', 'EA'),
  ('PRIPB3X', 'Printing cost PB3X barrier', 'Printing', 'EA'),
  ('PRISTD', 'Printing Standard Barriers', 'Printing', 'EA'),
  ('PRISTDUSM', 'Printing Standard for US Manufacturing', 'Printing', 'EA'),
  ('PRIV1', 'Printing V1', 'Printing', 'EA'),
  ('PRIV2', 'printing cost V2', 'Printing', 'EA'),
  ('PS15 C', 'Table PS 15 - CUT 960 x 1575', 'Slovak Cotton', 'EA'),
  ('PS20 C', 'Table PS 20 - CUT 960 x 1575mm', 'Slovak Cotton', 'EA'),
  ('PVC blanc', 'PVC Low and Bonar blanc uncut', 'PVC', 'Sq Meter'),
  ('PVCACH', 'Transparent PVC ACHILLES', 'PVC Strip', 'Sq Meter'),
  ('ROADF', 'ROAD TRANSPORT', null, null),
  ('RSP', 'Red Sea Project: generator noise control: acoustic barrier modelling', 'EB Admin', null),
  ('S200', 'S200 Poly - CUT', 'Acoustic Foam', 'EA'),
  ('SEAF', 'Sea Freight', null, null),
  ('SENIZOL ATaEB', 'SENIZOL AT a EB - CUT 960 x 1580mm', 'Slovak Cotton', 'EA'),
  ('SENIZOL EB3', 'SENIZOL EB 3 - V ROLKACH / 100% PES to supplier SK-TEX spol s.r.o.', 'Non Woven Textile', 'Ln Meter'),
  ('SENIZOLEB', 'SENIZOL EB - CUT 1000 x 1580 mm', 'Slovak Cotton', 'EA'),
  ('SENIZOLEB2', 'SENIZOL EB2 - CUT 960 x 1580mm', 'Slovak Cotton', 'EA'),
  ('SHP', 'Shipping', 'Printing', 'EA'),
  ('SHP-CFR', 'CFR to Port - (including transport and Insurance)', 'Printing', 'EA'),
  ('SNDB', 'SAND BAG', 'Bamida Manufacturing', 'EA'),
  ('SPR', 'Small Pack- ROLL 960 mm', 'Slovak Cotton', 'Ln Meter'),
  ('ST131 STEELGREY', 'ST-131 (steel grey)', 'Gortex', 'Ln Meter'),
  ('STIC', 'Stickers', 'Printing', 'Piece'),
  ('SupperBoly3D', 'Jilana SuperBoly 3D 1050 - ROLL 960mm', 'Non Woven Textile', 'Ln Meter'),
  ('TB1', 'Echo Barrier TB1 Sound Absorber', 'Finished Barriers', 'EA'),
  ('TRANSPORT', 'TRANSPORT', null, 'EA'),
  ('V12018', 'Echo Barrier V1', 'Finished Barriers', 'EA'),
  ('V1FRM', 'V1 FRAME', 'EB Admin', 'EA'),
  ('WBCUT', 'White Brace - CUT 960mm x 15880mm', 'Slovak Cotton', 'EA'),
  ('WF', 'Whisper Foam', 'Acoustic Foam', 'EA'),
  ('Wooden Pallet', 'Wooden Pallet 160x100', null, null),
  ('WSEN', 'Wave structure Senizol', 'PES Infill', 'Ln Meter')
ON CONFLICT (code) DO UPDATE
  SET description = EXCLUDED.description,
      product_group = EXCLUDED.product_group,
      base_unit = EXCLUDED.base_unit;

-- ----------------------------------------------------------------------------
-- 3. RLS — picklist pattern (read-all authenticated; writes service-role only)
-- ----------------------------------------------------------------------------
ALTER TABLE public.po_suppliers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.item_catalog ENABLE ROW LEVEL SECURITY;

DO $$
DECLARE t text;
BEGIN
  FOREACH t IN ARRAY ARRAY['po_suppliers','item_catalog']
  LOOP
    EXECUTE format('REVOKE ALL ON public.%I FROM anon', t);
    EXECUTE format('REVOKE INSERT, UPDATE, DELETE ON public.%I FROM authenticated', t);
    EXECUTE format('GRANT SELECT ON public.%I TO authenticated', t);
    EXECUTE format('DROP POLICY IF EXISTS "picklist readable by authenticated" ON public.%I', t);
    EXECUTE format(
      'CREATE POLICY "picklist readable by authenticated" ON public.%I FOR SELECT TO authenticated USING (true)', t);
  END LOOP;
END$$;
